name: "Simple Greet Action"
description: "Greets a user"

inputs:
  name:
    description: "Name to greet"
    required: true

runs:
  using: "composite"
  steps:
    - name: Print greeting
      shell: bash
      run: echo "Hello, ${{ inputs.name }}!"